### ISSUE TITLE
Fix proto Metric.getName.

### ISSUE THREAD

**Issue by songy23** [census-ecosystem/opencensus-go-exporter-stackdriver#101]
https://github.com/census-instrumentation/opencensus-proto/pull/184 removed `name` field from `metric` but the Stackdriver exporter still depends on it. It has caused build failures.

**Comment by icco** [comment]
Thanks!

**Comment by songy23** [comment]
To fix the build failures, please use the new tag in `go.mod` which includes the fix (`contrib.go.opencensus.io/exporter/stackdriver v0.9.2`). Apologies for the inconvenience.
