### ISSUE TITLE
monitoredresource.Autodetect(): PermissionDenied

### ISSUE THREAD

**Issue by mwuertinger** [census-ecosystem/opencensus-go-exporter-stackdriver#116]
When calling `monitoredresource.Autodetect()` on GKE the following log output appears:
```
Error retrieving gcp metadata: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
```

Environment:
opencensus-go-exporter-stackdriver: `v0.9.2`
Kubernetes: `1.11.7-gke.12`

**Comment by songy23** [comment]
This could be either the service role on this GKE doesn't have sufficient access to instance metadata (https://cloud.google.com/compute/docs/storing-retrieving-metadata), or GKE disabled metadata APIs (https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata). Can you try run this command and see what's the output?
```bash
$ curl -H 'Metadata-Flavor: Google' \
'http://metadata.google.internal/computeMetadata/v1/instance/attributes/disable-legacy-endpoints'
```

**Comment by mwuertinger** [comment]
Hi @songy23,

thanks a lot for your quick response! I executed the query both inside a pod on the cluster as well as directly on one of the nodes. In both cases I got a 404 error.

If I run curl without the last path component, I get:
```
$ curl -H 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/attributes/'
cluster-location
cluster-name
cluster-uid
configure-sh
created-by
enable-oslogin
gci-ensure-gke-docker
gci-update-strategy
google-compute-enable-pcid
instance-template
kube-env
kube-labels
kubelet-config
user-data
```

**Comment by songy23** [comment]
This seems to be the first case, since the received metadata doesn't include instance attributes. Please add the following permissions to your service account that runs GKE:
> Permissions required for this task
> To perform this task, you must have the following permissions.
> * compute.projects.get on the project if just getting metadata
> * compute.instances.get on the instance if just getting metadata

**Comment by mwuertinger** [comment]
I only got the `disable-legacy-endpoints` endpoint to work by specifically setting `--metadata disable-legacy-endpoints=true` when creating the node pool.

I eliminated the original error by using a service account for the application and setting `GOOGLE_APPLICATION_CREDENTIALS` to point to the service account JSON file.
