### ISSUE TITLE
Update dependencies and tag a new version

### ISSUE THREAD

**Issue by jle** [census-ecosystem/opencensus-go-exporter-stackdriver#126]
go.mod uses old versions of some dependencies that cause `go get -u` to fail:

```
	cloud.google.com/go v0.37.1
	contrib.go.opencensus.io/exporter/ocagent v0.4.9
```

See: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/59

Adding this here to track the work. Thank you.

**Comment by songy23** [comment]
Fixed with https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/125 and https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/releases/tag/v0.10.1.
