### ISSUE TITLE
My gauge are always global and not K8S or GCE

### ISSUE THREAD

**Issue by sebglon** [census-ecosystem/opencensus-go-exporter-stackdriver#133]
This is my stackdriver config

```
	opt := stackdriver.Options{
		// MetricPrefix helps uniquely identify your metrics.
		//	ProjectID:    project,
		MetricPrefix: "backup",
		OnError: func(err error) {
			log.Printf("Failed to send metrics on stackdriver: %v", err.Error())
		},
		Context: cont,
		Timeout: 5 * time.Second,
		//MonitoredResource: monitoredresource.Autodetect(),
		ReportingInterval: 1 * time.Minute,
		ResourceDetector:  auto.Detect,
	}
```
When i run my app on GKE, all my gauge have resource type Global but not K8S_container

On debug i can't see everything to set them on this method: https://github.com/census-instrumentation/opencensus-go/blob/5ae9166f90ff989c557e45fcb9592ac59afa0fa0/metric/metricexport/reader.go#L183

**Comment by teelahti** [comment]
I have been debugging the same exact issue: After autodetect everything looks correct and autodetected resource type is GKEContainer with all the necessary fields set, but all exported metrics end up as "global" in Stackdriver. Please let me know if there is any data I could provide to help fixing this issue; for me this problem renders Stackdriver exporter useless at the moment and I'm keen on getting this fixed.

The relevant parts of my code are as follows (error management etc. removed for clarity): 

	
	view.Register(MyView1, MyView2)

	sd, _ := stackdriver.NewExporter(stackdriver.Options{
		MetricPrefix: “foo”,
		MonitoredResource: monitoredresource.Autodetect().
		DefaultMonitoringLabels = &stackdriver.Labels{},
	})

	sd.StartMetricsExporter()
	defer sd.StopMetricsExporter()
	defer sd.Flush()

**Comment by songy23** [comment]
This seems to be related to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/109. The new metrics export doesn't respect the resource set in the options. /cc @rghetia

**Comment by sebglon** [comment]
#140
