### ISSUE TITLE
go.mod and Gopkg.toml call for different protobuf versions

### ISSUE THREAD

**Issue by grantr** [census-ecosystem/opencensus-go-exporter-stackdriver#141]
Currently go.mod calls for 1.3.1, Gopkg.toml calls for 1.1.0. What's the actual dependency here?

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/433871bd6e79575d6ffbbd10add24d3ab1f90a9c/go.mod#L9

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/e393203a62e3c9286501f3195fe2f2ca1e35e115/Gopkg.toml#L32-L34

Note that in Gopkg.toml, the version specifier `1.1.0` is interpreted as `1.1.x` (see the **Note** at https://golang.github.io/dep/docs/Gopkg.toml.html#version), so 1.3.x is not allowed by the current constraint.

In https://github.com/knative/eventing I have a dependency (https://github.com/google/cel-go) that relies on protobuf 1.3.0, and I'm using `dep`. I'd like to avoid having to override protobuf if possible :)

**Comment by bogdandrutu** [comment]
@songy23 any update on this?

**Comment by songy23** [comment]
@rghetia Do we still need to support Gopkg? I saw in opentelemetry-go (https://github.com/open-telemetry/opentelemetry-go) we no longer support it.

**Comment by rghetia** [comment]
we don't need to support Gopkg.
