### ISSUE TITLE
Clean up various implementations of resources.

### ISSUE THREAD

**Issue by songy23** [census-ecosystem/opencensus-go-exporter-stackdriver#144]
Only keep https://github.com/census-instrumentation/opencensus-go/tree/master/resource with the updated resource types/keys, and remove everything else.

**Comment by bogdandrutu** [comment]
Status?

**Comment by songy23** [comment]
Mostly fixed by https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/155. There're some outdated options related to resource, I'll send a PR to remove it.
