### ISSUE TITLE
Should LastValue aggregation be exported as MetricKind GAUGE?

### ISSUE THREAD

**Issue by ramonza** [census-ecosystem/opencensus-go-exporter-stackdriver#15]
Context: https://cloud.google.com/monitoring/api/v3/metrics-details

Seems like LastValue should map to a GAUGE type metric since it represents an instantaneous value.

**Comment by songy23** [comment]
Yes, this is in our specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Export.md#aggregation-to-metric.

**Comment by songy23** [comment]
I also updated the OC-Go main repo in https://github.com/census-instrumentation/opencensus-go/pull/737 before.
