### ISSUE TITLE
Compilation broken after change to resource package

### ISSUE THREAD

**Issue by fastest963** [census-ecosystem/opencensus-go-exporter-stackdriver#153]
I gather from https://github.com/census-ecosystem/opencensus-go-resource/commit/c636715d96813e034abd3111b795ac4de4e8275e that the `resourcekeys` package was moved to `go.opencensus.io/resource/resourcekeys` but that repo doesn't contain any GCP* constants like the previous one did

Currently this cannot be built until this is resolved.

**Comment by rghetia** [comment]
#155 fixes the issue.

**Comment by rghetia** [comment]
fixed by #155 and is now released in v0.12.0.
