### ISSUE TITLE
Metrics exporter fails even though no custom metrics are registered

### ISSUE THREAD

**Issue by tchap** [census-ecosystem/opencensus-go-exporter-stackdriver#170]
Please answer these questions before submitting a bug report.

### What version of the Exporter are you using?

v0.12.2

### What version of OpenCensus are you using?

v0.22.0

### What version of Go are you using?

1.12.7

### What did you do?
If possible, provide a recipe for reproducing the error.

```golang
exporter, _ := stackdriver.NewExporter(stackdriver.Options{
    MonitoredResource: monitoredresource.Autodetect(),
    OnError: func(err error) {
        logger.Error("Stackdriver exporter failed.", zap.Error(err))
    },
})

exporter.StartMetricsExporter()
defer exporter.StopMetricsExporter()
```

### What did you expect to see?

I was expecting to see Stackdriver exporter running successfully, particularly when no custom stats are registered. Now I have no idea what is breaking Stackdriver exporter and it is blocking me from implementing what I need.

### What did you see instead?

`Stackdriver exporter failed.`

### Additional context

This is the log entry from Google Cloud:

```
 jsonPayload: {
  caller:  "stackdriver/init.go:40"   
  error:  "rpc error: code = InvalidArgument desc = Missing span display name!"   
  labels: {…}   
  message:  "Stackdriver exporter failed."   
  serviceContext: {…}   
  stacktrace:  "github.com/...
	/src/internal/stackdriver/init.go:40
contrib.go.opencensus.io/exporter/stackdriver.Options.handleError
	/root/go/pkg/mod/contrib.go.opencensus.io/exporter/stackdriver@v0.12.2/stackdriver.go:417
contrib.go.opencensus.io/exporter/stackdriver.(*traceExporter).uploadSpans
	/root/go/pkg/mod/contrib.go.opencensus.io/exporter/stackdriver@v0.12.2/trace.go:137
contrib.go.opencensus.io/exporter/stackdriver.newTraceExporterWithClient.func1
	/root/go/pkg/mod/contrib.go.opencensus.io/exporter/stackdriver@v0.12.2/trace.go:67
google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1
	/root/go/pkg/mod/google.golang.org/api@v0.6.0/support/bundler/bundler.go:272"   
  ts:  1562776665.9896464   
 }
```

**Comment by tchap** [comment]
I mean, the question would be whether a single error like this blocks the whole export or not. I cannot see metrics registered by me in the cloud, so I jumped to the conclusion that this is the cause. Maybe not?

**Comment by tchap** [comment]
Ok, it seems our metrics are actually pushed, I will just need to disable logging, which is said, but what can I do. Marking this as closed I guess...

**Comment by tchap** [comment]
Well, no, then the error is printed into `stderr` and it is spamming logs still...

**Comment by tchap** [comment]
Ok, setting the callback to an empty function works. I am being stupid...

**Comment by rogerhub** [comment]
Here's the problem:
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/e19adcf31cc85e158538dcd7e742e1d54d80f23b/stats.go#L146

`&metricexport.Reader{}` should be `metricexport.NewReader()` instead.

The metricexport library creates spans using the reader's name, and so if no name is given in the reader, then stackdriver rejects the span.
See here:
https://github.com/census-instrumentation/opencensus-go/blob/f24e56296b3a742d13b8368bbb1e831f9b0d2c7f/metric/metricexport/reader.go#L178

Feel free to re-open this if you want it fixed.

**Comment by tchap** [comment]
This should be fixed, right? I can send a PR...
