### ISSUE TITLE
Transitive dependency on "testing" registers test flags

### ISSUE THREAD

**Issue by mabn** [census-ecosystem/opencensus-go-exporter-stackdriver#229]
### What version of the Exporter are you using?
v0.12.7

### What version of OpenCensus are you using?
v0.22.1

### What version of Go are you using?
go version go1.12.8 darwin/amd64

### What did you do?
Running following code shows help for a bunch of `-test.xxx` flags

```
package main

import (
	"flag"
	"fmt"

	"contrib.go.opencensus.io/exporter/stackdriver"
)

func main() {
	flag.PrintDefaults()
	if false {
		fmt.Println(stackdriver.Options{})
	}
}
```

### What did you expect to see?
Nothing

### What did you see instead?
```go
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
(...)
```

### Additional context
I'd like "help" for a program to only show the flags I care about. I suspect that this can be solved by simply renaming `metrics_test_utils.go` to `metrics_test_utils_test.go`

**Comment by ascherkus** [comment]
Confirmed latest master branch has this fixed!
