### ISSUE TITLE
Provide convenience constructors for MonitoredResource types

### ISSUE THREAD

**Issue by ramonza** [census-ecosystem/opencensus-go-exporter-stackdriver#24]
Custom metrics (as produced by this exporter) are only compatible with a handful of MonitoredResource types. These have a fairly complicated set of properties associated with them. We should provide strongly-typed constructor functions to correctly build these MonitoredResources.

We could also consider an "Autodetect" MonitoredResource, which would rely on auto-detecting based on the runtime environment (Java currently does this).

**Comment by songy23** [comment]
Obsolete.
