### ISSUE TITLE
0.13.5 was tagged, but not yet released?

### ISSUE THREAD

**Issue by ukai** [census-ecosystem/opencensus-go-exporter-stackdriver#284]
https://pkg.go.dev/contrib.go.opencensus.io/exporter/stackdriver?tab=versions shows 0.13.5 is available,
but https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/releases says 0.13.4 is the latest release.

what is the status of 0.13.5?

**Comment by dashpole** [comment]
Sorry, I forgot to mark it latest.  It is now marked as the latest release.
