### ISSUE TITLE
Import cycle

### ISSUE THREAD

**Issue by jadekler** [census-ecosystem/opencensus-go-exporter-stackdriver#30]
```
$  go get -u contrib.go.opencensus.io/exporter/stackdriver
import cycle not allowed
package contrib.go.opencensus.io/exporter/stackdriver
	imports cloud.google.com/go/monitoring/apiv3
	imports google.golang.org/api/transport
	imports google.golang.org/api/transport/http
	imports contrib.go.opencensus.io/exporter/stackdriver
```

**Comment by jadekler** [comment]
To be more specific, we get this import cycle when we change https://github.com/google/google-api-go-client/blob/master/transport/http/go18.go#L22 to the new path.

**Comment by rakyll** [comment]
You shouldn't import the exporter. Exporters should be set by the user. If you are trying to import the propagation format, use https://godoc.org/contrib.go.opencensus.io/exporter/stackdriver/propagation.
