### ISSUE TITLE
go: warning: github.com/prometheus/prometheus@v2.5.0+incompatible: retracted by module author

### ISSUE THREAD

**Issue by ukai** [census-ecosystem/opencensus-go-exporter-stackdriver#301]
Please answer these questions before submitting a bug report.

### What version of the Exporter are you using?
contrib.go.opencensus.io/exporter/stackdriver@v0.13.12

### What version of OpenCensus are you using?
go.opencensus.io@v0.23.0

### What version of Go are you using?
go 1.18.1

### What did you do?
If possible, provide a recipe for reproducing the error.

go get

### What did you expect to see?

no warning

### What did you see instead?

go warns
go: warning: github.com/prometheus/prometheus@v2.5.0+incompatible: retracted by module author

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/go.mod#L14

need to update go.mod?

**Comment by dashpole** [comment]
See https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/302
