### ISSUE TITLE
pkg/monitoredresource.Autodetect(): causes me to vendor aws-sdk-go

### ISSUE THREAD

**Issue by ahmetb** [census-ecosystem/opencensus-go-exporter-stackdriver#35]
```
vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
```
has imports:
```
18:	"github.com/aws/aws-sdk-go/aws/ec2metadata"
19:	"github.com/aws/aws-sdk-go/aws/session"
```

but importing `stackdriver/monitoredresource` causes me to vendor `github.com/aws/aws-sdk-go/aws` in my godep package.

I'm not using aws at all, so it's not right for me to have aws sdk end up in my final binary.

There are ways to avoid this such as building a wrapper that satisfies an interface.

**Comment by rakyll** [comment]
We are considering to implement https://github.com/census-instrumentation/opencensus-specs/pull/162 to detect monitored resources and thinking about splitting resource detection into a different package.

The auto-detection will be at the new resource package.

```
import "contrib.go.opencensus.io/resource"

resource.Autodetect()
```

And GCP and AWS will have split packages for detection.

**Comment by ramonza** [comment]
I think we should split packages as follow:
- separate packages for each cloud provider
- separate package for autodetect that imports all of the above

Then if you know which cloud provider you want to support, you only import the package you need and you can avoid importing the autodetect package (which will pull in all providers).

**Comment by rghetia** [comment]
once https://github.com/census-instrumentation/opencensus-go/pull/878 is committed we can deprecate autodetect. ChainDetector() can replace autodetect.

**Comment by songy23** [comment]
Duplicated of https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/144.
