### ISSUE TITLE
The recommended reporting period for the Monitoring API is 60 seconds.

### ISSUE THREAD

**Issue by rimey** [census-ecosystem/opencensus-go-exporter-stackdriver#36]
There appears to be no recommendation here for a suitable reporting period for the Monitoring API. The [sample code](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/81c8a5149790e4a46e36488795ba9b1f6e41396f/examples/stats/main.go#L59) sets it to one second:

`	view.SetReportingPeriod(1 * time.Second)
`

If this corresponds to the period of the time series data sent to the Monitoring API, it is way too short. [Best practice](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#writing-ts) is a period of 60 seconds.

Apologies if I have misunderstood and this does not actually determine the period between points in a time series. I am not very familiar with OpenCensus.

**Comment by songy23** [comment]
Default reporting period is [10 seconds](https://github.com/census-instrumentation/opencensus-go/blob/78fb78ae664f0f83af1fb8acf8817a77dcd8f4ef/stats/view/worker.go#L50). In the example we made the period shorter so that users don't need to wait too long to see the output.

/cc @ramonza @odeke-em

**Comment by rimey** [comment]
Writing to a time series more frequently than every ten seconds is not supported and is generally going to fail. I would recommend guiding users towards the 60-second best practice, to reduce the likelihood of them being surprised by a large bill.

**Comment by rimey** [comment]
Unless it's feasible to have the exporter override the default reporting period, I think it's going to be necessary to have guidance in the README.md to recommend overriding it.

It may also be necessary to review how the issue is presented in the opencensus-go project.

**Comment by ramonza** [comment]
I agree with @rimey we should change the examples to 60s. In another example on the website, we had something shorter (I don't remember if it was 1 second or something else) and this caused problems with Stackdriver.
