### ISSUE TITLE
Improve error message for distribution with no buckets [was: Stackdriver export is failing]

### ISSUE THREAD

**Issue by jadekler** [census-ecosystem/opencensus-go-exporter-stackdriver#41]
I have a simple pubsub app using stackdriver exporter and some views. When I go to stackdriver, I see my stats but without any resource (I expect "global"). I put some logging around [`handleUpload`](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stats.go#L139-L143) and notice it's erroring out:

```
rpc error: code = InvalidArgument desc = Field timeSeries[1].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.
2018/09/11 15:28:45 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = Field timeSeries[1].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.
```

[Full program is here.](https://gist.github.com/jadekler/5636acc62eb0048cad15206ef5587650)

`PublishSuccessMillisView` looks like this:

```
PublishSuccessMillis = stats.Int64(statsPrefix+"publish_success_millis", "Number of milliseconds to publish a message", stats.UnitMilliseconds)

...

PublishSuccessMillisView *view.View = distView(PublishSuccessMillis)

...

func distView(m *stats.Int64Measure) *view.View {
	return &view.View{
		Name:        m.Name(),
		Description: m.Description(),
		TagKeys:     []tag.Key{subscriptionKey},
		Measure:     m,
		Aggregation: view.Distribution(),
	}
}
```

It gets used as such:

```
millis := end.Sub(start).Nanoseconds() / 1000000
stats.Record(ctx, PublishSuccessMillis.M(millis))
```

**Comment by jadekler** [comment]
Totally possible I'm trying to record time the wrong way. Is that the case? (related: https://github.com/census-instrumentation/opencensus-specs/issues/44)

**Comment by odeke-em** [comment]
@jadekler please firstly change this line https://gist.github.com/jadekler/5636acc62eb0048cad15206ef5587650#file-dupe_oc-go-L61
to
```go
view.SetReportingPeriod(62 * time.Second)
```
to firstly rule out any hasty time series recordings as per https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/36 and https://github.com/census-instrumentation/opencensus-go/issues/909

**Comment by ramonza** [comment]
@jadekler the problem is likely that you have no buckets in the distribution specified in the view.

**Comment by jadekler** [comment]
@ramonza What is a bucket? How do I get a bucket? Perhaps there's documentation that I'm lacking - if so, please feel free to link and close.

**Comment by songy23** [comment]
@jadekler The documentation is here: https://godoc.org/go.opencensus.io/stats/view#Distribution. The problem is although OpenCensus allows `Distribution` with no bucket bounds, Stackdriver doesn't support it.

 Can you try modifying your view to something like:
```go
func distView(m *stats.Int64Measure) *view.View {
	return &view.View{
		Name:        m.Name(),
		Description: m.Description(),
		TagKeys:     []tag.Key{subscriptionKey},
		Measure:     m,
		Aggregation: view.Distribution(0), // Should have at least one bucket bound.
	}
}
```

**Comment by jadekler** [comment]
@songy23 Thanks for the pointers, I'll try this tomorrow or Monday. re:

> The problem is although OpenCensus allows Distribution with no bucket bounds, Stackdriver doesn't support it.

Is it unreasonable to expect the stackdriver exporter to somehow raise an error, or panic, if that's the case?

**Comment by jadekler** [comment]
Actually, we ended up going with a view with `Aggregation: view.Sum()`.  I'll leave this open while we discuss the remaining question I had above.

**Comment by ramonza** [comment]
@jadekler to be fair, it did log an error, although I think we could certainly improve the error message by doing some basic validation client-side.

**Comment by jadekler** [comment]
@ramonza Actually, that's my fmt.Println heh. Is there a way to make opencensus verbosely log?

**Comment by ramonza** [comment]
The default if no OnError is provided should be to log the error, is this not happening? If not, could you send a PR with your changes to add the logging?

**Comment by jadekler** [comment]
Ah, I was unaware of OnError. I'll leave y'all to decide if you want this issue as a placeholder for better docs, or if you'd like to just close it that's solid for me too.

**Comment by jadekler** [comment]
SGTM
