### ISSUE TITLE
Update gke_container resource to k8s_container, gce_instance to k8s_node.

### ISSUE THREAD

**Issue by durp** [census-ecosystem/opencensus-go-exporter-stackdriver#49]
Per https://cloud.google.com/monitoring/kubernetes-engine/migration if using the new Kubernetes monitoring, the currently Autodetected ResourceTypes  will need to be changed:
`gke_container` -> `k8s_container`
`gce_instance` -> `k8s_node`

**Comment by songy23** [comment]
cc @mayurkale22

**Comment by gaplyk** [comment]
any news on the topic?
