### ISSUE TITLE
Wrong version info in the agent field of exported span 

### ISSUE THREAD

**Issue by gottwald** [census-ecosystem/opencensus-go-exporter-stackdriver#5]
The stackdriver exporter reports the wrong OC version info in the user-agent.

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/b98abe41e381c878749ef1aa9eb0798616afbb43/stats.go#L51

Maybe the version info in `census-instrumentation/opencensus-go` should be moved out of the internal package, so that it can be imported from exporters. Otherwise it may always run out of sync.

**Comment by ramonza** [comment]
Fixed in https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/11
