### ISSUE TITLE
The package depends on 'github.com/aws/aws-sdk-go'

### ISSUE THREAD

**Issue by andreisobchuck** [census-ecosystem/opencensus-go-exporter-stackdriver#60]
Is it ok that the package depends on 'github.com/aws/aws-sdk-go'?
The total time to get all depencies in Google Cloud Builder is big.

**Comment by andreisobchuck** [comment]
Is it ok that the package depends on 'github.com/aws/aws-sdk-go'? 
The total time to get all depencies in Google Cloud Builder is big.

**Comment by odeke-em** [comment]
Thank you filing this issue @andreisobchuck and welcome to the OpenCensus project!

This project needs to keep monitored resources and particularly for AWS as per https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/899e456273f5c46d23aef8f0c66e899d7d1e17f4/monitoredresource/aws_identity_doc_utils.go hence we cannot remove that dependency.

/cc @rakyll @bogdandrutu

**Comment by songy23** [comment]
Duplicated of https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/144.
