### ISSUE TITLE
blank HTTP Host variable is logged

### ISSUE THREAD

**Issue by jmhodges** [census-ecosystem/opencensus-go-exporter-stackdriver#62]
Blank /http/host values are being sent because this exporter uses the r.URL.Host variable (that is often empty) and doesn't log the r.Host (which is often provided) on http.Request objects.

The reason why is described in this stackoverflow answer: https://stackoverflow.com/questions/42921567/what-is-the-difference-between-host-and-url-host-for-golang-http-request

I've not found a case in which the r.URL.Host was the desired one since HTTP/1.1 and newer (which require Host headers) is standard now.

**Comment by jmhodges** [comment]
opencensus-go fixed their version of this ticket (https://github.com/census-instrumentation/opencensus-go/issues/992). It'd be cool to have this one fixed, too!

**Comment by rghetia** [comment]
fixed as a result of https://github.com/census-instrumentation/opencensus-go/pull/1036

**Comment by jmhodges** [comment]
Oh! Great!
