### ISSUE TITLE
metrics: add conversion from metricsproto.SummaryValue

### ISSUE THREAD

**Issue by odeke-em** [census-ecosystem/opencensus-go-exporter-stackdriver#66]
Coming here from https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/65#discussion_r240080931
converting to metricsproto.SummaryValue to Stackdriver monitoring/v3 Proto is not straight forward and as per v0.8.0 of this code https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/tree/v0.8.0 doesn't even yet support this conversion.

This issue is to track that conversion for posterity and to keep it on our radar.

**Comment by songy23** [comment]
Already fixed in https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/152.
